# Site settings
title: jgoizueta
email: jgoizueta@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes to myself.
baseurl: "" # the subpath of your site, e.g. /blog/
url : "http://www.jgoizueta.net"
#twitter_username: jekyllrb
github_username:  jgoizueta

# Build settings
markdown: kramdown
keep_files: ['downloads']
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  # extensions: [ "fenced_code_blocks" ]
  extensions: ['autolink', 'footnotes', 'smart']

redcarpet:
  extensions: [ "no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data" ]
